### ISSUE TITLE
Deploy de páginas automático no GitHub Pages 

### ISSUE THREAD

**Issue by bpires** [kuldseks/hiring-coders-3_css-portfolio#1]
Hey João!

Vi a postagem com seu portfolio no Linkedin, dei uma olhada no seu repo aqui no GitHub e vi que você não fez o deploy do seu portfolio. Mesmo sendo só um exercício ou maneira de documentar teu crescimento, é interessante que a gente possa entrar no repo e ver o resultado final on line!

Então a dica que eu queria te dar é a de tornar o deploy do teu site automático pelo GitHub Pages. Ele funciona apenas para páginas estáticas (sem necessidade de back end).

Quando você ativa o Pages, ele publica o que estiver na página, buscando inicialmente um index.html no diretório raiz (root), caso ele não encontre, ele utilizará o README.md para gerar a página, e ela ficará acessível no endereço no formato https://username.github.io/repositoryname/, assim como seus subdiretórios no `https://username.github.io/repositoryname/subdirectoryname`.

Segue o fio 🧵:

<details>
<summary>1. Com teu repositório aberto, vai em <strong>Settings:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583682-308fe8dc-b818-4332-a5cf-d6d129aec066.png)

</details>

<details>
<summary>2. No menu esquerdo, procura a aba <strong>Pages:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583711-2752046b-6b5b-44fa-8106-6bc9042fb0d0.png)

</details>
<details>
<summary>3. Em <strong>Source</strong>, seleciona a branch <strong>Main:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583899-f6bcabfd-8ff1-4476-b92b-7b7ce54d2021.png)

</details>
<details>
<summary>4. Mantém na pasta <strong>/root</strong> e lembra de <strong>salvar:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583944-df06b6d9-9461-4b1e-9e76-fcf9a4f61f7e.png)

</details>

<details>
<summary>5. Pronto, o GitHub vai fazer o deploy automático do teu repositório e das subpastas para o GitHub Pages, pode levar uns bons minutos (você pode ver o status em "actions"), mas quando terminar você pode ir pela url ou ver na área <strong>Environments</strong> no menu direito do teu repositório a tua página publicada:</summary>

![image](https://user-images.githubusercontent.com/86871991/162584041-18ae4faf-f0bc-4f58-8939-28db18ae23c4.png)

PS: Na área de environments, clica em `github-pages` e depois em `View deployment`

![image](https://user-images.githubusercontent.com/86871991/162584105-4bc18fda-8b97-4381-831c-ad6646037455.png)

</details>

Depois de configurado, toda alteração que você fizer no repositório, ele faz um novo deploy automático!

Testa essa funcionalidade nesse repositório aqui e coloca teu site no ar! 😄

Precisar de ajuda, só falar. Depois lembra de fechar essa issue.

Keep going! 🔥

---

PS: O GIF ficou massa, mas te sugiro colocar mais informações no seu README.md do teu repo, como: qual era o desafio, as stacks que você utilizou, o que aprendeu etc. Isso enriquece teu GitHub e te ajuda no futuro na hora de exibir projetos para um recrutador p. ex. 

PS2: Meu irmão fez um site simples que tem alguns elementos legais pra colocar no README de projetos, dá uma conferida: [README Creator | Projects](https://readmecreator.herokuapp.com/project). Dá para você pegar algumas boas ideias e deixar com a sua cara depois! 

Abs!

**Comment by kuldseks** [comment]
Fala, Rafael! Tudo  bem? 

Muito obrigado pelas dicas :) 

Já fiz o deploy aqui do GitHub e no netfly, segue:
https://kuldseks-portfolio-css-hiringcoders3.netlify.app
https://kuldseks.github.io/hiring-coders-3_css-portfolio/ 

Vou utilizar o site que seu irmão desenvolveu sim, sem dúvidas rsrs

Obrigado pela força 👯

**Comment by bpires** [comment]
ficou top, tamo junto 👊🏻
